### PR TITLE
Move "external-ssh-keys" to the right parent folder

### PR DESCRIPTION
**Pull request by jrpedrianes**

### CODE REVIEW

**Comment by achetronic** [comment]
Hey, why you suggest moving this folder? I put this folder outside in purpose to make it easier for the people to find the files

**Comment by jrpedrianes** [comment]
In a previous refactor I saw that you moved all the terraform code to the terraform folder, so if we left the "external-ssh-keys" there, terraform never reach it.

https://github.com/achetronic/metal-cloud/blob/f011a9ca923a80cb59de26925d3d891d9ff83c62/terraform/modules/workload/storage.tf#L51C1-L51C1

I thought that you want to move all inside the temporal folder, hence the change, but also I can change the terraform code to search the keys in an upper level.

**Comment by achetronic** [comment]
> In a previous refactor I saw that you moved all the terraform code to the terraform folder, so if we left the "external-ssh-keys" there, terraform never reach it.
> 
> https://github.com/achetronic/metal-cloud/blob/f011a9ca923a80cb59de26925d3d891d9ff83c62/terraform/modules/workload/storage.tf#L51C1-L51C1
> 
> I thought that you want to move all inside the temporal folder, hence the change, but also I can change the terraform code to search the keys in an upper level.

Hello @jrpedrianes I tested and confirmed the bug. The problem is in the previous refactor I had not taken into account the module_path

ATM the PR is stuck for two reasons:
- I am currently adding several features to support better ARM64 generic environments and more auth methods with no pain
- You introduced out of the scope changes in this PR. Each PR needs to be accountable in changes, so the scope is required to be limited as some of them will be accepted and some others potentially not. Could you make each proposal on different PRs?

**Comment by jrpedrianes** [comment]
Sorry, I pushed some modifications to the main branch by mistake, but I revert it. 

This PR only have the code to fix the problem that Terraform doesn't find the ssh keys.

**Comment by jrpedrianes** [comment]
In the fork that I have, I solve other problem that faces me related to the network, but that is another story :P, I moved it to another branch.

**Comment by jrpedrianes** [comment]
If you want I can try to let the ssh folder in the root and change the terraform code or maybe wait for your changes. Whatever is best to avoid disturbing your changes.

**Comment by achetronic** [comment]
> In the fork that I have, I "fix" other problem that faces me related to the network, but that is another story :smile:, I moved it to another branch.

Let's discuss it on a different issue? just open it an start the discussion. I am doing some changes on that file too just because of the same

**Comment by jrpedrianes** [comment]
> > If you want I can try to let the ssh folder in the root and change the terraform code or maybe wait for your changes. Whatever is best to avoid disturbing your changes.
> 
> Hey, no problem about it. I was thinking what is better, if to move all the folder or to jusr fix the location and add a variable to be able to custom the path.
> 
> What i want is to evolve the module to be a bit more future-proof
> 
> WDYT is better and why?

I think that If you want that this code at the end evolves into a more isolated terraform module and, in the future, convert it into a terraform provider, seems that is better to add an "input variable" to the module, and if is configured it will take it into account.

**Comment by achetronic** [comment]
> > > If you want I can try to let the ssh folder in the root and change the terraform code or maybe wait for your changes. Whatever is best to avoid disturbing your changes.
> > 
> > Hey, no problem about it. I was thinking what is better, if to move all the folder or to jusr fix the location and add a variable to be able to custom the path.
> > 
> > What i want is to evolve the module to be a bit more future-proof
> > 
> > WDYT is better and why?
> 
> I think that If you want that this code at the end evolves into a more isolated terraform module and, in the future, convert it into a terraform provider, seems that is better to add an "input variable" to the module, and if is configured it will take it into account.

Hey, I am already on conversion into a more isolated module inside the same repo. If you see it, it's versioned with the releases, and in the fixes i will introduce, some improvements comes, for example the global config params, just to make it extendable

Unfortunately, I think it's not a good idea to convert it into a provider as it is using the most common libvirt provider under the hood. I see this repo more as a module that helps using it much more easier with some advanced configurations already working under the hood
(Something like ready to go, with almost no knowledge coming from the people)

**Comment by jrpedrianes** [comment]
Oook

The option to add a variable indicating the ssh key folder maybe is the better choice, allows to the user have many keys organized as the user wants: environment, servers...

**Comment by achetronic** [comment]
> Oook
> 
> The option to add a variable indicating the ssh key folder maybe is the better choice, allows to the user have many keys organized as the user wants: environment, servers...

Not documented yet, but the branch with most of the changes that will be merged [is this one](https://github.com/achetronic/metal-cloud/tree/feat/refactor-into-module)

It would be awesome if you test the branch to get some feedback

After this changes are merged and version is released, the next ones are those related with the networks management

Time to give a star to the repository? ⭐ 😄

**Comment by jrpedrianes** [comment]
> 

Star given, of course sure :smile_cat: 

I just tested the new terraform code with my test machine, an x86 machine with ubuntu 22.04, and I managed to make it work but with some little modifications:
* I needed to change this line https://github.com/achetronic/metal-cloud/blob/feat/refactor-into-module/terraform/terraform.tf#L21 with this "qemu+ssh://${var.globals.ssh_connection.username}@${var.globals.ssh_connection.host}/system?keyfile=${var.globals.ssh_connection.private_key_path}&no_verify=1" because I only have stored the public key in my machine and the private key is stored in a secured vault connected using a socket. So it is not possible to pass the private key file.
* Also I had problems with the networks, maybe now you are testing with another distribution because you have configured the network using 'enp3sXXXX' and for me is not correct, I saw the comment there, and I think that is not easy to know what is the network name to configure.

**Comment by achetronic** [comment]
> 

Hey @jrpedrianes, regarding to those two things:
- the argument `sshauth=privkey` is part of the chain to say you will be logging with an SSH key, independently if you are using only the public piece for it. You can see the documentation[ in this section, but in the bottom of the anchor](https://libvirt.org/uri.html#libssh-and-libssh2-transport)
- Regarding to the networks, only the `en` prefix is predictable. This means depending on the system you will have `**en**p1s0` or `**en**s0` because it depends on the number of ports you have dedicated to that, or if the card update the information regarding to the port, etc,[ as you can see here](https://juncotic.com/eth0-enp0s3-nombres-interfaces-red-linux/) so the thing is that the best way is to ask to the OS about the interfaces. ATM it has been a luck that the code worked for that amount of people. I want to make it stable and predictable for everyone, so I will do a script just to ask the OS about the interfaces to fix it

Let me see if I can work on it this to have a working solution by these days, but at this moment of the refactor, just not to merge too many changes in the main branch, I will go merging all these (considering your first point is not a bug in my side), and in the next version (following weeks) I will attack the networking prediction problem. Until then, I recommend you to use the release version just not to break anything (or fork the repo) because these changes are completely needed if we want to have a stable module in the near future

**Comment by achetronic** [comment]
Closed as most of the things are [resolved here](https://github.com/achetronic/metal-cloud/releases/tag/v1.0.0). Please, to start discussions about new changes, open an issue with the problem and the proposal and let's discuss there about the things 🙏🏼

**Comment by jrpedrianes** [comment]
Ok, I was reviewing the new branch and looks pretty good (the mac trick solves many problems :P).

Regarding the `sshauth` argument passed to livbirt connection, in my case I need this `sshauth=privkey,agent` as I don't have stored the private key in my host and is an IdentityAgent, pointing to a socket, which resolves the challenge.

If you want that I test it on my test machine, please let me know.

**Comment by achetronic** [comment]
> Ok, I was reviewing the new branch and looks pretty good (the mac trick solves many problems :P).
> 
> Regarding the `sshauth` argument passed to livbirt connection, in my case I need this `sshauth=privkey,agent` as I don't have stored the private key in my host and is an IdentityAgent, pointing to a socket, which resolves the challenge.
> 
> If you want that I test it on my test machine, please let me know.

Well, we still have to discuss about fixing the IPs for the NAT networks too in the issue you opened, but true that MAC trick helps a bit :)

regarding to the argument `sshauth=privkey,agent` I agree with the change and the order of the arguments, to give priority to the privkey but does not discard the public. So please, open a PR with it and lets release the fix for everyone

**Pull request closed without merging**
